### ISSUE TITLE
[PCB!!!!!!!!!] Graeme, this is fucking urgent!!!!!

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#104]
You're playing chubby bunny with shitty ideas.

**Comment by GlenNicholls** [comment]
@graemeDnf I just want to thank you for actually responding to my issues...

**Comment by graemeDnf** [comment]
You open so many of them, it's hard to keep track sometimes. Glad I could do that for you...

**Comment by bandtank** [comment]
lol. FYI - you can do this in the issue search box to find the issues assigned to a specific person:

`is:open assignee:bandtank`

It helps if you want to find your todo list when the tasks aren't included in milestones and if they don't have labels.
