### ISSUE TITLE
Python is a toy, we must discern this

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#16]
https://github.com/GlenNicholls/solar_tracking_project/blob/c96660d3944b09754b287629c967a6d3fd50009d/src/main.py#L61

This should be get_location(). IMO, Python is a toy and should be treated as such. We don't want it to know that it has the same rights as any other language. Segregate the language and the coding gods will thank you.

I'm really starting to get off topic from writing this resistance and rev paper...

**Comment by bandtank** [comment]
Are you drunk?
