### ISSUE TITLE
[PCB] Switching noise from alarm condition causes uC to briefly enter reset due to TTL threshold

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#23]
RESET_N pin of uC has been having issues when the alarm pin goes low causing device to briefly enter reset which causes glitching on power control pin (led to false positive during testing). Need to add 10K pullup to fix the metastable condition.

Probing without the pullup, the voltage is 1.54V (3.3V Vcc), but drops to 1.48V during an alarm condition before slowly coming back up to 1.54V where it comes out of reset. Probing the RESET_N pin caused this brief reset not to occur, so I think that capacitance caused the device not to drop below the TTL threshold.

**Comment by bandtank** [comment]
The reset pin definitely needs to be pulled high. You should also add a
capacitor to ground.

**Comment by GlenNicholls** [comment]
We have this going through a level shifter, should the LPF be on the high or low side? Does it matter?

**Comment by bandtank** [comment]
Is the schematic updated? If so, where should I be looking?

**Comment by GlenNicholls** [comment]
@graemeDnf , feel free to close this when the PCB has the pullup noted by ISSUE#23 in the schematic.
