### ISSUE TITLE
[SCH] R23 states 250mOhm, but BOM has 300mOhm

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#35]
In the schematic, R23 for the current sensor is shown to be 250mOhm, but the BOM has a 300mOhm on order. Probably not a big deal, but should be accounted for in calculations and should also be adjusted to whichever is the correct value.

**Comment by graemeDnf** [comment]
300m was significantly cheaper in the 2512 package, so I put that on the BOM. I ensured it would work with the new value, so I'll update it when I get a chance

**Comment by GlenNicholls** [comment]
okay cool, I just wanted to make sure.
