### ISSUE TITLE
[PCB] Switch connection error (Graeme messed up, mk2)

### ISSUE THREAD

**Issue by graemeDnf** [GlenNicholls/solar_tracking_project#37]
attiny pin wired to incorrect side of pushbutton switch

**Comment by GlenNicholls** [comment]
Can you be more specific with a pic? I'm not seeing the issue unless it's the via, but I don't know where that goes.

**Comment by GlenNicholls** [comment]
Also, remove R37, R6, and C5 from the PCB as these aren't needed since debouncing in software works more than well enough. Just let me know where I should connect the wires for the button instead and I'll test it on Thursday.
