### ISSUE TITLE
Unnecessary interrupt flag clearing

### ISSUE THREAD

**Issue by bandtank** [GlenNicholls/solar_tracking_project#5]
https://github.com/GlenNicholls/solar_tracking_project/blob/89bd5b87050819dc284a78d5802128b977265ed5/misc_dev/attiny84a/src/power_circuit_ctrl/power_circuit_ctrl/main.c#L268

https://github.com/GlenNicholls/solar_tracking_project/blob/89bd5b87050819dc284a78d5802128b977265ed5/misc_dev/attiny84a/src/power_circuit_ctrl/power_circuit_ctrl/main.c#L305

https://github.com/GlenNicholls/solar_tracking_project/blob/89bd5b87050819dc284a78d5802128b977265ed5/misc_dev/attiny84a/src/power_circuit_ctrl/power_circuit_ctrl/main.c#L329

Being explicit is never bad, but this isn't necessary to do because the flags are cleared automatically when the ISR executes. Unless you have a specific reason to clear the flag at the end of the ISR, such as masking a new interrupt request for the same ISR while it's already being serviced, I would let it clear the flag on its own. There are rare, yet subtle, consequences to doing things like this that may not always be obvious up front.

**Comment by GlenNicholls** [comment]
Just removed these for the time being. Will add later if we run into a situation where we need it.
