### ISSUE TITLE
[PCB] USB micro B female not close enough to edge of board and needs revision

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#57]
The usb connector needs to be closer to the edge of the PCB. The silkscreen box edge for the USB connector should be touching the edge of the PCB.

Also, we need something with pins that go down into the PCB as the force to plug it in will rip the connector off the board.

**Comment by graemeDnf** [comment]
Moved header to the edge of the board. Did you solder the larger pads on the header to the board as well? it seems like the pin breakout boards still have a usb header mounted on the surface in the same way, so I'm not sure if using something like that will make a difference

**Comment by GlenNicholls** [comment]
@graemeDnf I thought I did, I watched the solder flow under the scope, but it doesn't look like it made a good connection since I don't have an oven or a heat gun... I guess I wasn't careful enough. The two smaller pads were definitely connected, but the two big ones looked pretty clean after the break. With that said, having something with pins that go into the board will give more support for external forces. I looked around online, and this seems to be a really common issue with the type of connector that we chose unless you're conscious about plugging USB in.

Considering we're pulling straight from the charge controller USB, we don't have many other options, but I think it will work fine if we can solder a couple pins in a via.

If you look at the pi, it has something like this and seems to work pretty well. Now that I think about it, we should definitely change to a button that has a vertical push as well so we don't run into this again with that.

**Comment by GlenNicholls** [comment]
We need something similar to this:

https://www.mouser.com/ProductDetail/Hirose-Connector/ZX62D-B-5PA830?qs=sGAEpiMZZMvYKGyZxp8jxgWbApVXx0RFRAN%2fG9EvgO8%3d

**Comment by GlenNicholls** [comment]
Also, if it is possible, try to extend the 5 pin pads for the power/data lines to make soldering the device easier

**Comment by graemeDnf** [comment]
Ended up using this https://www.digikey.com/product-detail/en/amphenol-fci/10118194-0001LF/609-4618-1-ND/2785382. I tried making a PCB symbol with extended pads, but couldn't get designspark to play nice with the necessary spacing tolerance, so I went with the amphenol connector because it had a pcb footprint available
