### ISSUE TITLE
[PISW] Make flash gui

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#62]
Tony, can you make us a flash gui and couple it as tight as possible to our application code?

**Comment by bandtank** [comment]
Holy shit. I saw 'Make flash gui' on my phone's notification and I almost had a heart attack. Funny, yet cruel.

Closing with prejudice.

**Comment by GlenNicholls** [comment]
good, I had a feeling this would induce a similar response.
