### ISSUE TITLE
Note todo

### ISSUE THREAD

**Issue by GlenNicholls** [GlenNicholls/solar_tracking_project#8]
https://github.com/GlenNicholls/solar_tracking_project/blob/c96660d3944b09754b287629c967a6d3fd50009d/src/main.py#L9

**Comment by GlenNicholls** [comment]
This is noted now in makefile issue#46

**Comment by bandtank** [comment]
If you type issues as pound and then the number, it will link them automatically. E.g., #46 instead of Issue#36.
